
-- generated by elm_rs


module Data exposing (..)

import Dict exposing (Dict)
import Http
import Json.Decode
import Json.Encode
import Orgauth.Data exposing (UserId(..), userIdDecoder, userIdEncoder)
import Url.Builder


resultEncoder : (e -> Json.Encode.Value) -> (t -> Json.Encode.Value) -> (Result e t -> Json.Encode.Value)
resultEncoder errEncoder okEncoder enum =
    case enum of
        Ok inner ->
            Json.Encode.object [ ( "Ok", okEncoder inner ) ]
        Err inner ->
            Json.Encode.object [ ( "Err", errEncoder inner ) ]


resultDecoder : Json.Decode.Decoder e -> Json.Decode.Decoder t -> Json.Decode.Decoder (Result e t)
resultDecoder errDecoder okDecoder =
    Json.Decode.oneOf
        [ Json.Decode.map Ok (Json.Decode.field "Ok" okDecoder)
        , Json.Decode.map Err (Json.Decode.field "Err" errDecoder)
        ]


type alias Allocation =
    { id : Int
    , project : Int
    , duration : Int
    , allocationdate : Int
    , description : String
    , createdate : Int
    , changeddate : Int
    , creator : Int
    }


allocationEncoder : Allocation -> Json.Encode.Value
allocationEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.int) struct.id )
        , ( "project", (Json.Encode.int) struct.project )
        , ( "duration", (Json.Encode.int) struct.duration )
        , ( "allocationdate", (Json.Encode.int) struct.allocationdate )
        , ( "description", (Json.Encode.string) struct.description )
        , ( "createdate", (Json.Encode.int) struct.createdate )
        , ( "changeddate", (Json.Encode.int) struct.changeddate )
        , ( "creator", (Json.Encode.int) struct.creator )
        ]


type alias ExtraField =
    { n : String
    , v : String
    }


extraFieldEncoder : ExtraField -> Json.Encode.Value
extraFieldEncoder struct =
    Json.Encode.object
        [ ( "n", (Json.Encode.string) struct.n )
        , ( "v", (Json.Encode.string) struct.v )
        ]


type alias PayEntry =
    { id : Int
    , project : Int
    , user : Int
    , duration : Int
    , paytype : PayType
    , paymentdate : Int
    , description : String
    , createdate : Int
    , changeddate : Int
    , creator : Int
    }


payEntryEncoder : PayEntry -> Json.Encode.Value
payEntryEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.int) struct.id )
        , ( "project", (Json.Encode.int) struct.project )
        , ( "user", (Json.Encode.int) struct.user )
        , ( "duration", (Json.Encode.int) struct.duration )
        , ( "paytype", (payTypeEncoder) struct.paytype )
        , ( "paymentdate", (Json.Encode.int) struct.paymentdate )
        , ( "description", (Json.Encode.string) struct.description )
        , ( "createdate", (Json.Encode.int) struct.createdate )
        , ( "changeddate", (Json.Encode.int) struct.changeddate )
        , ( "creator", (Json.Encode.int) struct.creator )
        ]


type PayType
    = Invoiced
    | Paid


payTypeEncoder : PayType -> Json.Encode.Value
payTypeEncoder enum =
    case enum of
        Invoiced ->
            Json.Encode.string "Invoiced"
        Paid ->
            Json.Encode.string "Paid"

type alias Project =
    { id : Int
    , name : String
    , description : String
    , dueDays : Maybe (Int)
    , extraFields : List (ExtraField)
    , invoiceIdTemplate : String
    , invoiceSeq : Int
    , payer : String
    , payee : String
    , genericTask : String
    , public : Bool
    , rate : Maybe (Float)
    , currency : Maybe (String)
    , createdate : Int
    , changeddate : Int
    }


projectEncoder : Project -> Json.Encode.Value
projectEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.int) struct.id )
        , ( "name", (Json.Encode.string) struct.name )
        , ( "description", (Json.Encode.string) struct.description )
        , ( "due_days", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.int)) struct.dueDays )
        , ( "extra_fields", (Json.Encode.list (extraFieldEncoder)) struct.extraFields )
        , ( "invoice_id_template", (Json.Encode.string) struct.invoiceIdTemplate )
        , ( "invoice_seq", (Json.Encode.int) struct.invoiceSeq )
        , ( "payer", (Json.Encode.string) struct.payer )
        , ( "payee", (Json.Encode.string) struct.payee )
        , ( "generic_task", (Json.Encode.string) struct.genericTask )
        , ( "public", (Json.Encode.bool) struct.public )
        , ( "rate", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.float)) struct.rate )
        , ( "currency", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.currency )
        , ( "createdate", (Json.Encode.int) struct.createdate )
        , ( "changeddate", (Json.Encode.int) struct.changeddate )
        ]


type alias ProjectMember =
    { id : Int
    , name : String
    , role : Role
    }


projectMemberEncoder : ProjectMember -> Json.Encode.Value
projectMemberEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.int) struct.id )
        , ( "name", (Json.Encode.string) struct.name )
        , ( "role", (roleEncoder) struct.role )
        ]


type PublicMessageX
    = PmGetProjectTime (Int)


publicMessageXEncoder : PublicMessageX -> Json.Encode.Value
publicMessageXEncoder enum =
    case enum of
        PmGetProjectTime inner ->
            Json.Encode.object [ ( "PmGetProjectTime", Json.Encode.int inner ) ]

type Role
    = Member
    | Admin
    | Observer


roleEncoder : Role -> Json.Encode.Value
roleEncoder enum =
    case enum of
        Member ->
            Json.Encode.string "Member"
        Admin ->
            Json.Encode.string "Admin"
        Observer ->
            Json.Encode.string "Observer"

type alias SaveAllocation =
    { id : Maybe (Int)
    , project : Int
    , duration : Int
    , allocationdate : Int
    , description : String
    }


saveAllocationEncoder : SaveAllocation -> Json.Encode.Value
saveAllocationEncoder struct =
    Json.Encode.object
        [ ( "id", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.int)) struct.id )
        , ( "project", (Json.Encode.int) struct.project )
        , ( "duration", (Json.Encode.int) struct.duration )
        , ( "allocationdate", (Json.Encode.int) struct.allocationdate )
        , ( "description", (Json.Encode.string) struct.description )
        ]


type alias SavePayEntry =
    { id : Maybe (Int)
    , project : Int
    , user : Int
    , duration : Int
    , paytype : PayType
    , paymentdate : Int
    , description : String
    }


savePayEntryEncoder : SavePayEntry -> Json.Encode.Value
savePayEntryEncoder struct =
    Json.Encode.object
        [ ( "id", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.int)) struct.id )
        , ( "project", (Json.Encode.int) struct.project )
        , ( "user", (Json.Encode.int) struct.user )
        , ( "duration", (Json.Encode.int) struct.duration )
        , ( "paytype", (payTypeEncoder) struct.paytype )
        , ( "paymentdate", (Json.Encode.int) struct.paymentdate )
        , ( "description", (Json.Encode.string) struct.description )
        ]


type alias SaveProjectInvoice =
    { id : Int
    , invoiceSeq : Int
    , extraFields : List (ExtraField)
    }


saveProjectInvoiceEncoder : SaveProjectInvoice -> Json.Encode.Value
saveProjectInvoiceEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.int) struct.id )
        , ( "invoice_seq", (Json.Encode.int) struct.invoiceSeq )
        , ( "extra_fields", (Json.Encode.list (extraFieldEncoder)) struct.extraFields )
        ]


type alias SaveProjectTime =
    { project : Int
    , savetimeentries : List (SaveTimeEntry)
    , deletetimeentries : List (Int)
    , savepayentries : List (SavePayEntry)
    , deletepayentries : List (Int)
    , saveallocations : List (SaveAllocation)
    , deleteallocations : List (Int)
    }


saveProjectTimeEncoder : SaveProjectTime -> Json.Encode.Value
saveProjectTimeEncoder struct =
    Json.Encode.object
        [ ( "project", (Json.Encode.int) struct.project )
        , ( "savetimeentries", (Json.Encode.list (saveTimeEntryEncoder)) struct.savetimeentries )
        , ( "deletetimeentries", (Json.Encode.list (Json.Encode.int)) struct.deletetimeentries )
        , ( "savepayentries", (Json.Encode.list (savePayEntryEncoder)) struct.savepayentries )
        , ( "deletepayentries", (Json.Encode.list (Json.Encode.int)) struct.deletepayentries )
        , ( "saveallocations", (Json.Encode.list (saveAllocationEncoder)) struct.saveallocations )
        , ( "deleteallocations", (Json.Encode.list (Json.Encode.int)) struct.deleteallocations )
        ]


type alias SaveTimeEntry =
    { id : Maybe (Int)
    , project : Int
    , user : Int
    , description : String
    , startdate : Int
    , enddate : Int
    , ignore : Bool
    }


saveTimeEntryEncoder : SaveTimeEntry -> Json.Encode.Value
saveTimeEntryEncoder struct =
    Json.Encode.object
        [ ( "id", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.int)) struct.id )
        , ( "project", (Json.Encode.int) struct.project )
        , ( "user", (Json.Encode.int) struct.user )
        , ( "description", (Json.Encode.string) struct.description )
        , ( "startdate", (Json.Encode.int) struct.startdate )
        , ( "enddate", (Json.Encode.int) struct.enddate )
        , ( "ignore", (Json.Encode.bool) struct.ignore )
        ]


type alias SavedProjectEdit =
    { project : Project
    , members : List (ProjectMember)
    }


savedProjectEditEncoder : SavedProjectEdit -> Json.Encode.Value
savedProjectEditEncoder struct =
    Json.Encode.object
        [ ( "project", (projectEncoder) struct.project )
        , ( "members", (Json.Encode.list (projectMemberEncoder)) struct.members )
        ]


type UserMessageX
    = UmGetProjectList
    | UmSaveProjectEdit (SavedProjectEdit)
    | UmGetProjectEdit (Int)
    | UmSaveProjectInvoice (SaveProjectInvoice)
    | UmGetProjectTime (Int)
    | UmSaveProjectTime (SaveProjectTime)
    | UmGetUserTime
    | UmGetAllUsers


userMessageXEncoder : UserMessageX -> Json.Encode.Value
userMessageXEncoder enum =
    case enum of
        UmGetProjectList ->
            Json.Encode.string "UmGetProjectList"
        UmSaveProjectEdit inner ->
            Json.Encode.object [ ( "UmSaveProjectEdit", savedProjectEditEncoder inner ) ]
        UmGetProjectEdit inner ->
            Json.Encode.object [ ( "UmGetProjectEdit", Json.Encode.int inner ) ]
        UmSaveProjectInvoice inner ->
            Json.Encode.object [ ( "UmSaveProjectInvoice", saveProjectInvoiceEncoder inner ) ]
        UmGetProjectTime inner ->
            Json.Encode.object [ ( "UmGetProjectTime", Json.Encode.int inner ) ]
        UmSaveProjectTime inner ->
            Json.Encode.object [ ( "UmSaveProjectTime", saveProjectTimeEncoder inner ) ]
        UmGetUserTime ->
            Json.Encode.string "UmGetUserTime"
        UmGetAllUsers ->
            Json.Encode.string "UmGetAllUsers"

allocationDecoder : Json.Decode.Decoder Allocation
allocationDecoder =
    Json.Decode.succeed Allocation
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "duration" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "allocationdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "description" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "changeddate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "creator" (Json.Decode.int)))


extraFieldDecoder : Json.Decode.Decoder ExtraField
extraFieldDecoder =
    Json.Decode.succeed ExtraField
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "n" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "v" (Json.Decode.string)))


type alias ListProject =
    { id : Int
    , name : String
    , role : Role
    }


listProjectDecoder : Json.Decode.Decoder ListProject
listProjectDecoder =
    Json.Decode.succeed ListProject
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "role" (roleDecoder)))


payEntryDecoder : Json.Decode.Decoder PayEntry
payEntryDecoder =
    Json.Decode.succeed PayEntry
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "user" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "duration" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "paytype" (payTypeDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "paymentdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "description" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "changeddate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "creator" (Json.Decode.int)))


payTypeDecoder : Json.Decode.Decoder PayType
payTypeDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Invoiced" ->
                            Json.Decode.succeed Invoiced
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Paid" ->
                            Json.Decode.succeed Paid
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]

projectDecoder : Json.Decode.Decoder Project
projectDecoder =
    Json.Decode.succeed Project
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "description" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "due_days" (Json.Decode.nullable (Json.Decode.int))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "extra_fields" (Json.Decode.list (extraFieldDecoder))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "invoice_id_template" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "invoice_seq" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "payer" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "payee" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "generic_task" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "public" (Json.Decode.bool)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "rate" (Json.Decode.nullable (Json.Decode.float))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "currency" (Json.Decode.nullable (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "changeddate" (Json.Decode.int)))


type alias ProjectEdit =
    { project : Project
    , members : List (ProjectMember)
    }


projectEditDecoder : Json.Decode.Decoder ProjectEdit
projectEditDecoder =
    Json.Decode.succeed ProjectEdit
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (projectDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "members" (Json.Decode.list (projectMemberDecoder))))


projectMemberDecoder : Json.Decode.Decoder ProjectMember
projectMemberDecoder =
    Json.Decode.succeed ProjectMember
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "role" (roleDecoder)))


type alias ProjectTime =
    { project : Project
    , members : List (ProjectMember)
    , timeentries : List (TimeEntry)
    , payentries : List (PayEntry)
    , allocations : List (Allocation)
    }


projectTimeDecoder : Json.Decode.Decoder ProjectTime
projectTimeDecoder =
    Json.Decode.succeed ProjectTime
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (projectDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "members" (Json.Decode.list (projectMemberDecoder))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "timeentries" (Json.Decode.list (timeEntryDecoder))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "payentries" (Json.Decode.list (payEntryDecoder))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "allocations" (Json.Decode.list (allocationDecoder))))


roleDecoder : Json.Decode.Decoder Role
roleDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Member" ->
                            Json.Decode.succeed Member
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Admin" ->
                            Json.Decode.succeed Admin
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Observer" ->
                            Json.Decode.succeed Observer
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]

savedProjectEditDecoder : Json.Decode.Decoder SavedProjectEdit
savedProjectEditDecoder =
    Json.Decode.succeed SavedProjectEdit
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (projectDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "members" (Json.Decode.list (projectMemberDecoder))))


type ServerResponseX
    = SrProjectEdit (ProjectEdit)
    | SrProjectEditDenied
    | SrSavedProjectEdit (SavedProjectEdit)
    | SrSavedProjectEditDenied
    | SrSavedProjectInvoice (Project)
    | SrSavedProjectInvoiceDenied
    | SrProjectTime (ProjectTime)
    | SrProjectTimeDenied
    | SrProjectList (List (ListProject))
    | SrUserTime (List (TimeEntry))
    | SrAllUsers (List (User))


serverResponseXDecoder : Json.Decode.Decoder ServerResponseX
serverResponseXDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.map SrProjectEdit (Json.Decode.field "SrProjectEdit" (projectEditDecoder))
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "SrProjectEditDenied" ->
                            Json.Decode.succeed SrProjectEditDenied
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.map SrSavedProjectEdit (Json.Decode.field "SrSavedProjectEdit" (savedProjectEditDecoder))
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "SrSavedProjectEditDenied" ->
                            Json.Decode.succeed SrSavedProjectEditDenied
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.map SrSavedProjectInvoice (Json.Decode.field "SrSavedProjectInvoice" (projectDecoder))
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "SrSavedProjectInvoiceDenied" ->
                            Json.Decode.succeed SrSavedProjectInvoiceDenied
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.map SrProjectTime (Json.Decode.field "SrProjectTime" (projectTimeDecoder))
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "SrProjectTimeDenied" ->
                            Json.Decode.succeed SrProjectTimeDenied
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.map SrProjectList (Json.Decode.field "SrProjectList" (Json.Decode.list (listProjectDecoder)))
        , Json.Decode.map SrUserTime (Json.Decode.field "SrUserTime" (Json.Decode.list (timeEntryDecoder)))
        , Json.Decode.map SrAllUsers (Json.Decode.field "SrAllUsers" (Json.Decode.list (userDecoder)))
        ]

type alias TimeEntry =
    { id : Int
    , project : Int
    , user : Int
    , description : String
    , startdate : Int
    , enddate : Int
    , ignore : Bool
    , createdate : Int
    , changeddate : Int
    , creator : Int
    }


timeEntryDecoder : Json.Decode.Decoder TimeEntry
timeEntryDecoder =
    Json.Decode.succeed TimeEntry
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "user" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "description" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "startdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "enddate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "ignore" (Json.Decode.bool)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "changeddate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "creator" (Json.Decode.int)))


type alias User =
    { id : Int
    , name : String
    }


userDecoder : Json.Decode.Decoder User
userDecoder =
    Json.Decode.succeed User
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.string)))


