
-- generated by elm_rs


module TcProtocol exposing (..)

import Dict exposing (Dict)
import Http
import Json.Decode
import Json.Encode
import Orgauth.Data exposing (UserId(..), userIdDecoder, userIdEncoder)
import Url.Builder


resultEncoder : (e -> Json.Encode.Value) -> (t -> Json.Encode.Value) -> (Result e t -> Json.Encode.Value)
resultEncoder errEncoder okEncoder enum =
    case enum of
        Ok inner ->
            Json.Encode.object [ ( "Ok", okEncoder inner ) ]
        Err inner ->
            Json.Encode.object [ ( "Err", errEncoder inner ) ]


resultDecoder : Json.Decode.Decoder e -> Json.Decode.Decoder t -> Json.Decode.Decoder (Result e t)
resultDecoder errDecoder okDecoder =
    Json.Decode.oneOf
        [ Json.Decode.map Ok (Json.Decode.field "Ok" okDecoder)
        , Json.Decode.map Err (Json.Decode.field "Err" errDecoder)
        ]


type alias Project =
    { id : ProjectId
    , name : String
    , description : String
    , dueDays : Maybe (Int)
    , extraFields : List (ExtraField)
    , invoiceIdTemplate : String
    , invoiceSeq : Int
    , payer : String
    , payee : String
    , genericTask : String
    , public : Bool
    , rate : Maybe (Float)
    , currency : Maybe (String)
    , createdate : Int
    , changeddate : Int
    }


projectEncoder : Project -> Json.Encode.Value
projectEncoder struct =
    Json.Encode.object
        [ ( "id", (projectIdEncoder) struct.id )
        , ( "name", (Json.Encode.string) struct.name )
        , ( "description", (Json.Encode.string) struct.description )
        , ( "due_days", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.int)) struct.dueDays )
        , ( "extra_fields", (Json.Encode.list (extraFieldEncoder)) struct.extraFields )
        , ( "invoice_id_template", (Json.Encode.string) struct.invoiceIdTemplate )
        , ( "invoice_seq", (Json.Encode.int) struct.invoiceSeq )
        , ( "payer", (Json.Encode.string) struct.payer )
        , ( "payee", (Json.Encode.string) struct.payee )
        , ( "generic_task", (Json.Encode.string) struct.genericTask )
        , ( "public", (Json.Encode.bool) struct.public )
        , ( "rate", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.float)) struct.rate )
        , ( "currency", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.currency )
        , ( "createdate", (Json.Encode.int) struct.createdate )
        , ( "changeddate", (Json.Encode.int) struct.changeddate )
        ]


type alias ProjectTime =
    { project : Project
    , members : List (ProjectMember)
    , timeentries : List (TimeEntry)
    , payentries : List (PayEntry)
    , allocations : List (Allocation)
    }


projectTimeEncoder : ProjectTime -> Json.Encode.Value
projectTimeEncoder struct =
    Json.Encode.object
        [ ( "project", (projectEncoder) struct.project )
        , ( "members", (Json.Encode.list (projectMemberEncoder)) struct.members )
        , ( "timeentries", (Json.Encode.list (timeEntryEncoder)) struct.timeentries )
        , ( "payentries", (Json.Encode.list (payEntryEncoder)) struct.payentries )
        , ( "allocations", (Json.Encode.list (allocationEncoder)) struct.allocations )
        ]


type alias PayEntry =
    { id : Int
    , project : ProjectId
    , user : UserId
    , duration : Int
    , paytype : PayType
    , paymentdate : Int
    , description : String
    , createdate : Int
    , changeddate : Int
    , creator : UserId
    }


payEntryEncoder : PayEntry -> Json.Encode.Value
payEntryEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.int) struct.id )
        , ( "project", (projectIdEncoder) struct.project )
        , ( "user", (userIdEncoder) struct.user )
        , ( "duration", (Json.Encode.int) struct.duration )
        , ( "paytype", (payTypeEncoder) struct.paytype )
        , ( "paymentdate", (Json.Encode.int) struct.paymentdate )
        , ( "description", (Json.Encode.string) struct.description )
        , ( "createdate", (Json.Encode.int) struct.createdate )
        , ( "changeddate", (Json.Encode.int) struct.changeddate )
        , ( "creator", (userIdEncoder) struct.creator )
        ]


type alias ProjectMember =
    { id : UserId
    , name : String
    , role : Role
    }


projectMemberEncoder : ProjectMember -> Json.Encode.Value
projectMemberEncoder struct =
    Json.Encode.object
        [ ( "id", (userIdEncoder) struct.id )
        , ( "name", (Json.Encode.string) struct.name )
        , ( "role", (roleEncoder) struct.role )
        ]


type alias Allocation =
    { id : Int
    , project : ProjectId
    , duration : Int
    , allocationdate : Int
    , description : String
    , createdate : Int
    , changeddate : Int
    , creator : UserId
    }


allocationEncoder : Allocation -> Json.Encode.Value
allocationEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.int) struct.id )
        , ( "project", (projectIdEncoder) struct.project )
        , ( "duration", (Json.Encode.int) struct.duration )
        , ( "allocationdate", (Json.Encode.int) struct.allocationdate )
        , ( "description", (Json.Encode.string) struct.description )
        , ( "createdate", (Json.Encode.int) struct.createdate )
        , ( "changeddate", (Json.Encode.int) struct.changeddate )
        , ( "creator", (userIdEncoder) struct.creator )
        ]


type alias TimeEntry =
    { id : Int
    , project : ProjectId
    , user : UserId
    , description : String
    , startdate : Int
    , enddate : Int
    , ignore : Bool
    , createdate : Int
    , changeddate : Int
    , creator : UserId
    }


timeEntryEncoder : TimeEntry -> Json.Encode.Value
timeEntryEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.int) struct.id )
        , ( "project", (projectIdEncoder) struct.project )
        , ( "user", (userIdEncoder) struct.user )
        , ( "description", (Json.Encode.string) struct.description )
        , ( "startdate", (Json.Encode.int) struct.startdate )
        , ( "enddate", (Json.Encode.int) struct.enddate )
        , ( "ignore", (Json.Encode.bool) struct.ignore )
        , ( "createdate", (Json.Encode.int) struct.createdate )
        , ( "changeddate", (Json.Encode.int) struct.changeddate )
        , ( "creator", (userIdEncoder) struct.creator )
        ]


type TcMessageX
    = TmGetProjectList
    | TmSaveProjectEdit (SaveProjectEdit)
    | TmGetProjectEdit (ProjectId)
    | TmSaveProjectInvoice (SaveProjectInvoice)
    | TmGetProjectTime (ProjectId)
    | TmSaveProjectTime (SaveProjectTime)
    | TmGetUserTime
    | TmGetAllUsers


tcMessageXEncoder : TcMessageX -> Json.Encode.Value
tcMessageXEncoder enum =
    case enum of
        TmGetProjectList ->
            Json.Encode.string "TmGetProjectList"
        TmSaveProjectEdit inner ->
            Json.Encode.object [ ( "TmSaveProjectEdit", saveProjectEditEncoder inner ) ]
        TmGetProjectEdit inner ->
            Json.Encode.object [ ( "TmGetProjectEdit", projectIdEncoder inner ) ]
        TmSaveProjectInvoice inner ->
            Json.Encode.object [ ( "TmSaveProjectInvoice", saveProjectInvoiceEncoder inner ) ]
        TmGetProjectTime inner ->
            Json.Encode.object [ ( "TmGetProjectTime", projectIdEncoder inner ) ]
        TmSaveProjectTime inner ->
            Json.Encode.object [ ( "TmSaveProjectTime", saveProjectTimeEncoder inner ) ]
        TmGetUserTime ->
            Json.Encode.string "TmGetUserTime"
        TmGetAllUsers ->
            Json.Encode.string "TmGetAllUsers"

type ProjectId
    = Pid (Int)


projectIdEncoder : ProjectId -> Json.Encode.Value
projectIdEncoder enum =
    case enum of
        Pid inner ->
            Json.Encode.object [ ( "Pid", Json.Encode.int inner ) ]

type PublicMessageX
    = PmGetProjectTime (ProjectId)


publicMessageXEncoder : PublicMessageX -> Json.Encode.Value
publicMessageXEncoder enum =
    case enum of
        PmGetProjectTime inner ->
            Json.Encode.object [ ( "PmGetProjectTime", projectIdEncoder inner ) ]

type alias PrintInvoice =
    { id : String
    , payer : String
    , payee : String
    , items : List (InvoiceItem)
    , date : String
    , dueDate : Maybe (String)
    , extraFields : List (ExtraField)
    , currency : String
    }


printInvoiceEncoder : PrintInvoice -> Json.Encode.Value
printInvoiceEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.string) struct.id )
        , ( "payer", (Json.Encode.string) struct.payer )
        , ( "payee", (Json.Encode.string) struct.payee )
        , ( "items", (Json.Encode.list (invoiceItemEncoder)) struct.items )
        , ( "date", (Json.Encode.string) struct.date )
        , ( "due_date", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.dueDate )
        , ( "extra_fields", (Json.Encode.list (extraFieldEncoder)) struct.extraFields )
        , ( "currency", (Json.Encode.string) struct.currency )
        ]


type alias InvoiceItem =
    { description : String
    , duration : Float
    , rate : Float
    }


invoiceItemEncoder : InvoiceItem -> Json.Encode.Value
invoiceItemEncoder struct =
    Json.Encode.object
        [ ( "description", (Json.Encode.string) struct.description )
        , ( "duration", (Json.Encode.float) struct.duration )
        , ( "rate", (Json.Encode.float) struct.rate )
        ]


type Role
    = Member
    | Admin
    | Observer


roleEncoder : Role -> Json.Encode.Value
roleEncoder enum =
    case enum of
        Member ->
            Json.Encode.string "Member"
        Admin ->
            Json.Encode.string "Admin"
        Observer ->
            Json.Encode.string "Observer"

type PayType
    = Invoiced
    | Paid


payTypeEncoder : PayType -> Json.Encode.Value
payTypeEncoder enum =
    case enum of
        Invoiced ->
            Json.Encode.string "Invoiced"
        Paid ->
            Json.Encode.string "Paid"

type alias ExtraField =
    { n : String
    , v : String
    }


extraFieldEncoder : ExtraField -> Json.Encode.Value
extraFieldEncoder struct =
    Json.Encode.object
        [ ( "n", (Json.Encode.string) struct.n )
        , ( "v", (Json.Encode.string) struct.v )
        ]


type alias SaveProjectEdit =
    { project : SaveProject
    , members : List (SaveProjectMember)
    }


saveProjectEditEncoder : SaveProjectEdit -> Json.Encode.Value
saveProjectEditEncoder struct =
    Json.Encode.object
        [ ( "project", (saveProjectEncoder) struct.project )
        , ( "members", (Json.Encode.list (saveProjectMemberEncoder)) struct.members )
        ]


type alias SaveProjectMember =
    { id : UserId
    , delete : Bool
    , role : Role
    }


saveProjectMemberEncoder : SaveProjectMember -> Json.Encode.Value
saveProjectMemberEncoder struct =
    Json.Encode.object
        [ ( "id", (userIdEncoder) struct.id )
        , ( "delete", (Json.Encode.bool) struct.delete )
        , ( "role", (roleEncoder) struct.role )
        ]


type alias SaveProject =
    { id : Maybe (ProjectId)
    , name : String
    , description : String
    , dueDays : Maybe (Int)
    , extraFields : List (ExtraField)
    , invoiceIdTemplate : String
    , invoiceSeq : Int
    , payer : String
    , payee : String
    , genericTask : String
    , public : Bool
    , rate : Maybe (Float)
    , currency : Maybe (String)
    }


saveProjectEncoder : SaveProject -> Json.Encode.Value
saveProjectEncoder struct =
    Json.Encode.object
        [ ( "id", (Maybe.withDefault Json.Encode.null << Maybe.map (projectIdEncoder)) struct.id )
        , ( "name", (Json.Encode.string) struct.name )
        , ( "description", (Json.Encode.string) struct.description )
        , ( "due_days", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.int)) struct.dueDays )
        , ( "extra_fields", (Json.Encode.list (extraFieldEncoder)) struct.extraFields )
        , ( "invoice_id_template", (Json.Encode.string) struct.invoiceIdTemplate )
        , ( "invoice_seq", (Json.Encode.int) struct.invoiceSeq )
        , ( "payer", (Json.Encode.string) struct.payer )
        , ( "payee", (Json.Encode.string) struct.payee )
        , ( "generic_task", (Json.Encode.string) struct.genericTask )
        , ( "public", (Json.Encode.bool) struct.public )
        , ( "rate", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.float)) struct.rate )
        , ( "currency", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.currency )
        ]


type alias SavedProjectEdit =
    { project : Project
    , members : List (ProjectMember)
    }


savedProjectEditEncoder : SavedProjectEdit -> Json.Encode.Value
savedProjectEditEncoder struct =
    Json.Encode.object
        [ ( "project", (projectEncoder) struct.project )
        , ( "members", (Json.Encode.list (projectMemberEncoder)) struct.members )
        ]


type alias SaveProjectInvoice =
    { id : ProjectId
    , invoiceSeq : Int
    , extraFields : List (ExtraField)
    }


saveProjectInvoiceEncoder : SaveProjectInvoice -> Json.Encode.Value
saveProjectInvoiceEncoder struct =
    Json.Encode.object
        [ ( "id", (projectIdEncoder) struct.id )
        , ( "invoice_seq", (Json.Encode.int) struct.invoiceSeq )
        , ( "extra_fields", (Json.Encode.list (extraFieldEncoder)) struct.extraFields )
        ]


type alias SaveProjectTime =
    { project : ProjectId
    , savetimeentries : List (SaveTimeEntry)
    , deletetimeentries : List (Int)
    , savepayentries : List (SavePayEntry)
    , deletepayentries : List (Int)
    , saveallocations : List (SaveAllocation)
    , deleteallocations : List (Int)
    }


saveProjectTimeEncoder : SaveProjectTime -> Json.Encode.Value
saveProjectTimeEncoder struct =
    Json.Encode.object
        [ ( "project", (projectIdEncoder) struct.project )
        , ( "savetimeentries", (Json.Encode.list (saveTimeEntryEncoder)) struct.savetimeentries )
        , ( "deletetimeentries", (Json.Encode.list (Json.Encode.int)) struct.deletetimeentries )
        , ( "savepayentries", (Json.Encode.list (savePayEntryEncoder)) struct.savepayentries )
        , ( "deletepayentries", (Json.Encode.list (Json.Encode.int)) struct.deletepayentries )
        , ( "saveallocations", (Json.Encode.list (saveAllocationEncoder)) struct.saveallocations )
        , ( "deleteallocations", (Json.Encode.list (Json.Encode.int)) struct.deleteallocations )
        ]


type alias SaveTimeEntry =
    { id : Maybe (Int)
    , project : ProjectId
    , user : UserId
    , description : String
    , startdate : Int
    , enddate : Int
    , ignore : Bool
    }


saveTimeEntryEncoder : SaveTimeEntry -> Json.Encode.Value
saveTimeEntryEncoder struct =
    Json.Encode.object
        [ ( "id", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.int)) struct.id )
        , ( "project", (projectIdEncoder) struct.project )
        , ( "user", (userIdEncoder) struct.user )
        , ( "description", (Json.Encode.string) struct.description )
        , ( "startdate", (Json.Encode.int) struct.startdate )
        , ( "enddate", (Json.Encode.int) struct.enddate )
        , ( "ignore", (Json.Encode.bool) struct.ignore )
        ]


type alias SaveAllocation =
    { id : Maybe (Int)
    , project : ProjectId
    , duration : Int
    , allocationdate : Int
    , description : String
    }


saveAllocationEncoder : SaveAllocation -> Json.Encode.Value
saveAllocationEncoder struct =
    Json.Encode.object
        [ ( "id", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.int)) struct.id )
        , ( "project", (projectIdEncoder) struct.project )
        , ( "duration", (Json.Encode.int) struct.duration )
        , ( "allocationdate", (Json.Encode.int) struct.allocationdate )
        , ( "description", (Json.Encode.string) struct.description )
        ]


type alias SavePayEntry =
    { id : Maybe (Int)
    , project : ProjectId
    , user : UserId
    , duration : Int
    , paytype : PayType
    , paymentdate : Int
    , description : String
    }


savePayEntryEncoder : SavePayEntry -> Json.Encode.Value
savePayEntryEncoder struct =
    Json.Encode.object
        [ ( "id", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.int)) struct.id )
        , ( "project", (projectIdEncoder) struct.project )
        , ( "user", (userIdEncoder) struct.user )
        , ( "duration", (Json.Encode.int) struct.duration )
        , ( "paytype", (payTypeEncoder) struct.paytype )
        , ( "paymentdate", (Json.Encode.int) struct.paymentdate )
        , ( "description", (Json.Encode.string) struct.description )
        ]


type TcResponseX
    = TrProjectEdit (ProjectEdit)
    | TrProjectEditDenied
    | TrSavedProjectEdit (SavedProjectEdit)
    | TrSavedProjectEditDenied
    | TrSavedProjectInvoice (Project)
    | TrSavedProjectInvoiceDenied
    | TrProjectTime (ProjectTime)
    | TrProjectTimeDenied
    | TrProjectList (List (ListProject))
    | TrUserTime (List (TimeEntry))
    | TrAllUsers (List (User))
    | TrError (TimeClonkError)


tcResponseXDecoder : Json.Decode.Decoder TcResponseX
tcResponseXDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.map TrProjectEdit (Json.Decode.field "TrProjectEdit" (projectEditDecoder))
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "TrProjectEditDenied" ->
                            Json.Decode.succeed TrProjectEditDenied
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.map TrSavedProjectEdit (Json.Decode.field "TrSavedProjectEdit" (savedProjectEditDecoder))
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "TrSavedProjectEditDenied" ->
                            Json.Decode.succeed TrSavedProjectEditDenied
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.map TrSavedProjectInvoice (Json.Decode.field "TrSavedProjectInvoice" (projectDecoder))
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "TrSavedProjectInvoiceDenied" ->
                            Json.Decode.succeed TrSavedProjectInvoiceDenied
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.map TrProjectTime (Json.Decode.field "TrProjectTime" (projectTimeDecoder))
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "TrProjectTimeDenied" ->
                            Json.Decode.succeed TrProjectTimeDenied
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.map TrProjectList (Json.Decode.field "TrProjectList" (Json.Decode.list (listProjectDecoder)))
        , Json.Decode.map TrUserTime (Json.Decode.field "TrUserTime" (Json.Decode.list (timeEntryDecoder)))
        , Json.Decode.map TrAllUsers (Json.Decode.field "TrAllUsers" (Json.Decode.list (userDecoder)))
        , Json.Decode.map TrError (Json.Decode.field "TrError" (timeClonkErrorDecoder))
        ]

type PublicResponseX
    = PrProjectTime (ProjectTime)


publicResponseXDecoder : Json.Decode.Decoder PublicResponseX
publicResponseXDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.map PrProjectTime (Json.Decode.field "PrProjectTime" (projectTimeDecoder))
        ]

type alias ListProject =
    { id : ProjectId
    , name : String
    , role : Role
    }


listProjectDecoder : Json.Decode.Decoder ListProject
listProjectDecoder =
    Json.Decode.succeed ListProject
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (projectIdDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "role" (roleDecoder)))


type TimeClonkError
    = TeNotLoggedIn
    | TeInvalidLogin
    | TeOther (String)


timeClonkErrorDecoder : Json.Decode.Decoder TimeClonkError
timeClonkErrorDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "TeNotLoggedIn" ->
                            Json.Decode.succeed TeNotLoggedIn
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "TeInvalidLogin" ->
                            Json.Decode.succeed TeInvalidLogin
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.map TeOther (Json.Decode.field "TeOther" (Json.Decode.string))
        ]

projectIdDecoder : Json.Decode.Decoder ProjectId
projectIdDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.map Pid (Json.Decode.field "Pid" (Json.Decode.int))
        ]

projectDecoder : Json.Decode.Decoder Project
projectDecoder =
    Json.Decode.succeed Project
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (projectIdDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "description" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "due_days" (Json.Decode.nullable (Json.Decode.int))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "extra_fields" (Json.Decode.list (extraFieldDecoder))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "invoice_id_template" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "invoice_seq" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "payer" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "payee" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "generic_task" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "public" (Json.Decode.bool)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "rate" (Json.Decode.nullable (Json.Decode.float))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "currency" (Json.Decode.nullable (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "changeddate" (Json.Decode.int)))


type alias ProjectEdit =
    { project : Project
    , members : List (ProjectMember)
    }


projectEditDecoder : Json.Decode.Decoder ProjectEdit
projectEditDecoder =
    Json.Decode.succeed ProjectEdit
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (projectDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "members" (Json.Decode.list (projectMemberDecoder))))


projectTimeDecoder : Json.Decode.Decoder ProjectTime
projectTimeDecoder =
    Json.Decode.succeed ProjectTime
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (projectDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "members" (Json.Decode.list (projectMemberDecoder))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "timeentries" (Json.Decode.list (timeEntryDecoder))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "payentries" (Json.Decode.list (payEntryDecoder))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "allocations" (Json.Decode.list (allocationDecoder))))


payEntryDecoder : Json.Decode.Decoder PayEntry
payEntryDecoder =
    Json.Decode.succeed PayEntry
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (projectIdDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "user" (userIdDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "duration" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "paytype" (payTypeDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "paymentdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "description" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "changeddate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "creator" (userIdDecoder)))


projectMemberDecoder : Json.Decode.Decoder ProjectMember
projectMemberDecoder =
    Json.Decode.succeed ProjectMember
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (userIdDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "role" (roleDecoder)))


allocationDecoder : Json.Decode.Decoder Allocation
allocationDecoder =
    Json.Decode.succeed Allocation
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (projectIdDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "duration" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "allocationdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "description" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "changeddate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "creator" (userIdDecoder)))


savedProjectEditDecoder : Json.Decode.Decoder SavedProjectEdit
savedProjectEditDecoder =
    Json.Decode.succeed SavedProjectEdit
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (projectDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "members" (Json.Decode.list (projectMemberDecoder))))


timeEntryDecoder : Json.Decode.Decoder TimeEntry
timeEntryDecoder =
    Json.Decode.succeed TimeEntry
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "project" (projectIdDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "user" (userIdDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "description" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "startdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "enddate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "ignore" (Json.Decode.bool)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "createdate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "changeddate" (Json.Decode.int)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "creator" (userIdDecoder)))


type alias User =
    { id : UserId
    , name : String
    }


userDecoder : Json.Decode.Decoder User
userDecoder =
    Json.Decode.succeed User
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (userIdDecoder)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "name" (Json.Decode.string)))


roleDecoder : Json.Decode.Decoder Role
roleDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Member" ->
                            Json.Decode.succeed Member
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Admin" ->
                            Json.Decode.succeed Admin
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Observer" ->
                            Json.Decode.succeed Observer
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]

extraFieldDecoder : Json.Decode.Decoder ExtraField
extraFieldDecoder =
    Json.Decode.succeed ExtraField
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "n" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "v" (Json.Decode.string)))


payTypeDecoder : Json.Decode.Decoder PayType
payTypeDecoder = 
    Json.Decode.oneOf
        [ Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Invoiced" ->
                            Json.Decode.succeed Invoiced
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        , Json.Decode.string
            |> Json.Decode.andThen
                (\x ->
                    case x of
                        "Paid" ->
                            Json.Decode.succeed Paid
                        unexpected ->
                            Json.Decode.fail <| "Unexpected variant " ++ unexpected
                )
        ]

